### ISSUE TITLE
ADD meal popup

### ISSUE THREAD

**Issue by vvvt** [vvvt/foodi#7]
- [X] display meal information
- [X] display meal image
- [x] display button to start navigation

**Comment by SoulKa** [comment]
[This guide](https://developers.google.com/maps/documentation/urls/guide) should work for the navigation.
[Linking](https://docs.expo.io/versions/latest/workflow/linking/) can be used to open the navigation link and open the Google App if it is installed. Otherwise the browser is opened with the map
